In [ ]:
# Data Source: https://data.bts.gov/stories/s/fseh-ipec

# I am looking through sites to see what data is available. I am interested in working with csv or html if it is
# in a table. I am hoping to find 3 potential datasets to use in the project. Projects that don't end up using a 
# dataset declared in Project 1 will earn a maximum grade of C. 

# The dataset should be LARGE -  meaning that it has more than 100 rows and 10 columns to start. You may be engineering 
# more columns as you go along. The size of the dataset limits the potential story/stories that you can tell. 
# Little data = little points

In [4]:
# Cell 1 - only do as much here as it takes to get the dataset into your df to save on Reads.
# if the data is coming from a website, consider reading it here and once in a dataframe write your
# data locally to be less dependent on internet. 

import pandas as pd
 

dock_location_ds = 'Locations_of_Docked_Bikes.csv' 
dock_loc_df = pd.read_csv(dock_location_ds)
dock_loc_df.sample(10)
dock_loc_df.describe()

Missing Values:
the_geom            0
ID                  0
FAC_ID              0
BIKE_ID             6
SYSTEM_ID           0
SYSTEM_NAME         0
YEAR                0
ASOFDATE            0
FAC_NAME           32
ADDRESS             0
CITY                0
STATE               0
ZIPCODE             0
CBSA_CODE           2
LONGITUDE           0
LATITUDE            0
STATION_TYPE        0
launchDate          0
endDate         48403
dtype: int64
----------------------------------------

Overview of All Columns:
the_geom
ID
FAC_ID
BIKE_ID
SYSTEM_ID
SYSTEM_NAME
YEAR
ASOFDATE
FAC_NAME
ADDRESS
CITY
STATE
ZIPCODE
CBSA_CODE
LONGITUDE
LATITUDE
STATION_TYPE
launchDate
endDate
----------------------------------------
Value counts for the 'STATE' column:
STATE
NY    10562
IL     7190
CA     7163
MA     3079
DC     2664
FL     2632
TX     2542
PA     1997
MN     1930
VA     1799
OR     1730
OH     1478
CO     1341
WI     1147
MD     1020
TN      991
KS      953
HI      902
NJ      853
GA      824
AZ      768
NE      643
MI      567
ID      552
LA      473
IN      452
NC      440
UT      382
KY      358
SC      295
MO      271
OK      260
IA      233
AL      178
NV      170
WA       98
VT       91
WY       88
ND       63
CT       60
NH       50
NM       45
AR       12
SD        8
Name: count, dtype: int64
----------------------------------------

In [8]:
#Cell 2 - using things learned in Lessons 9 and 10 learn more about the data.

 
#Get to know my dataset

print(dock_loc_df.describe())

print(dock_loc_df.info())

missing_values = dock_loc_df.isnull().sum()
print("Missing Values:")
print(missing_values)
print('-' * 40)

##GIVE AN OVERVIEW OF ALL THE COLUMNS IN THE DATASET
doc_columns = dock_loc_df.columns.tolist()
print("\nOverview of All Columns:")
for col in doc_columns:
    print(col)
print('-' * 40)

#how many states are represented
state_value_counts = dock_loc_df['STATE'].value_counts()
print("Value counts for the 'STATE' column:")
print(state_value_counts)
print('-' * 40)
 
#how many sites were launched each year
launch_value_counts = dock_loc_df['launchDate'].value_counts()
print("Value counts for the 'Launch' column:")
print(launch_value_counts)
print('-' * 40)

# what questions come to mind

# How many locations were launched each year
# How many locations were ended each year
# Map locations both active and inactive
# Is availability increasing or decreasing
# I wonder what CBSA_Code means and if I need to incorporate that info.

                 ID     SYSTEM_ID          YEAR       ASOFDATE       ZIPCODE  \
count  59354.000000  59354.000000  59354.000000   59354.000000  59354.000000
mean   29690.266806     43.978788   2019.581646  201968.708427  46960.220777
std    17147.618664     35.149157      2.472687     245.548698  31737.194805
min        1.000000      1.000000   2015.000000  201512.000000   1002.000000
25%    14839.250000      8.000000   2018.000000  201812.000000  15212.000000
50%    29677.500000     42.000000   2020.000000  202012.000000  46204.000000
75%    44550.750000     60.000000   2022.000000  202207.000000  77009.000000
max    59288.000000    166.000000   2023.000000  202307.000000  98104.000000

          LONGITUDE      LATITUDE
count  59354.000000  59354.000000
mean     -90.575057     38.652774
std       18.431850      4.922558
min     -157.870423     21.267900
25%      -97.350089     37.716161
50%      -86.776120     40.461250
75%      -75.174070     41.867226
max      -70.753969     47.666145
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 59354 entries, 0 to 59353
Data columns (total 19 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   the_geom      59354 non-null  object
 1   ID            59354 non-null  int64
 2   FAC_ID        59354 non-null  object
 3   BIKE_ID       59348 non-null  object
 4   SYSTEM_ID     59354 non-null  int64
 5   SYSTEM_NAME   59354 non-null  object
 6   YEAR          59354 non-null  int64
 7   ASOFDATE      59354 non-null  int64
 8   FAC_NAME      59322 non-null  object
 9   ADDRESS       59354 non-null  object
 10  CITY          59354 non-null  object
 11  STATE         59354 non-null  object
 12  ZIPCODE       59354 non-null  int64
 13  CBSA_CODE     59352 non-null  object
 14  LONGITUDE     59354 non-null  float64
 15  LATITUDE      59354 non-null  float64
 16  STATION_TYPE  59354 non-null  object
 17  launchDate    59354 non-null  object
 18  endDate       10951 non-null  object
dtypes: float64(2), int64(5), object(12)
memory usage: 8.6+ MB
None
Missing Values:
the_geom            0
ID                  0
FAC_ID              0
BIKE_ID             6
SYSTEM_ID           0
SYSTEM_NAME         0
YEAR                0
ASOFDATE            0
FAC_NAME           32
ADDRESS             0
CITY                0
STATE               0
ZIPCODE             0
CBSA_CODE           2
LONGITUDE           0
LATITUDE            0
STATION_TYPE        0
launchDate          0
endDate         48403
dtype: int64
----------------------------------------

Overview of All Columns:
the_geom
ID
FAC_ID
BIKE_ID
SYSTEM_ID
SYSTEM_NAME
YEAR
ASOFDATE
FAC_NAME
ADDRESS
CITY
STATE
ZIPCODE
CBSA_CODE
LONGITUDE
LATITUDE
STATION_TYPE
launchDate
endDate
----------------------------------------
Value counts for the 'STATE' column:
STATE
NY    10562
IL     7190
CA     7163
MA     3079
DC     2664
FL     2632
TX     2542
PA     1997
MN     1930
VA     1799
OR     1730
OH     1478
CO     1341
WI     1147
MD     1020
TN      991
KS      953
HI      902
NJ      853
GA      824
AZ      768
NE      643
MI      567
ID      552
LA      473
IN      452
NC      440
UT      382
KY      358
SC      295
MO      271
OK      260
IA      233
AL      178
NV      170
WA       98
VT       91
WY       88
ND       63
CT       60
NH       50
NM       45
AR       12
SD        8
Name: count, dtype: int64
----------------------------------------
Value counts for the 'Launch' column:
launchDate
Sep-2015    10062
Jun-2013     7511
Sep-2010     5281
Aug-2013     3794
Jul-2016     3351
            ...
Jan-2014        6
Mar-2014        6
Mar-2023        5
Jul-2020        4
Aug-2021        3
Name: count, Length: 80, dtype: int64
----------------------------------------